package llm

type SastVerdict string

// 2. Create constants using iota (which auto-increments)
const (
	FAILURE   SastVerdict = "FAILURE"   // 0
	MALICIOUS SastVerdict = "MALICIOUS" // 1
	SAFE      SastVerdict = "SAFE"      // 2
)

type OllamaGenerateResponse struct {
	Response string `json:"response"` // Contains the raw inner string generated by the LLM
}
type OllamaGenerateRequest struct {
	Model  string `json:"model"`
	Prompt string `json:"prompt"`
	Stream bool   `json:"stream"`
	Format string `json:"format"` // Setting this to "json" activates JSON Mode
}
type JudgeVerdict struct {
	Verdict         string `json:"verdict"`          // "MALICIOUS", "SUSPICIOUS", or "SAFE"
	ConfidenceScore int    `json:"confidence_score"` // 0 to 100
	Summary         string `json:"summary"`          // Concise behavioral reasoning
}
